service: serverless-firehose-athena

provider:
  name: aws
  runtime: nodejs6.10
  region: us-west-2

package:
  exclude:
    - README.md
    - .envrc
    - .envrc.skeleton
    - package.json
    - node_modules/**
    - yarn.lock
    - tsconfig.json
    - .gitignore

functions:
  webhook:
    handler: src/webhook.execute
    environment:
      STAGE: ${env:STAGE}
    events:
      - http:
          path: /webhook
          method: post

plugins:
  - serverless-plugin-typescript
