service: serverless-kinesis-firehose

provider:
  name: aws
  runtime: nodejs6.10
  region: us-west-2
  iamRoleStatements:
  - Effect: Allow
    Action:
      - firehose:DeleteDeliveryStream
      - firehose:PutRecord
      - firehose:PutRecordBatch
      - firehose:UpdateDestination
    Resource: '*'

package:
  exclude:
    - README.md
    - .envrc
    - .envrc.skeleton
    - package.json
    - node_modules/**
    - yarn.lock
    - tsconfig.json
    - .gitignore

functions:
  webhook:
    handler: src/webhook.execute
    environment:
      STAGE: ${env:STAGE}
    events:
      - http:
          path: /webhook
          method: post

resources: ${file(resources.yml)}

plugins:
  - serverless-plugin-typescript
